Don't use FQN
lekoala/silverstripe-debugbar pull request #54
Opened 2017-07-11 05:43 UTC by Firesphere

Using the FQN in the queries tab makes the trace interfere with other information and add unnecessary information. Removing the FQN in favour of UQN makes it more readable.

2017-07-11 22:39 UTC, robbieaverill commented
Seems sensible. Maybe this could be a configurable option which is enabled by default e.g. "strip namespaces from DB classes" or something? Also could you fix the tests?

2017-07-12 02:19 UTC, Firesphere commented
Sounds a bit like overkill to me to have a config setting just for that, but sure :)

2017-07-12 02:29 UTC, Firesphere commented
Done :)

2017-07-12 02:31 UTC, robbieaverill requested changes

2017-07-12 02:31 UTC, robbieaverill commented on _config/debugbar.yml
> +  show_namespaces: false
This could just be another option in the definitions from line 9. Could you also name it something like "show namespaces in db profiling"?

2017-07-12 02:34 UTC, Firesphere commented on _config/debugbar.yml
> +  show_namespaces: false
Ah, overlooked that block.

I'm not a fan of long config names, I rather add a comment explaining what it does than writing complete works of Shakespeare as config name.

2017-07-12 02:36 UTC, robbieaverill commented on _config/debugbar.yml
> +  show_namespaces: false
If you bound it to the database collector class it'd be more obvious what it's relating to

2017-07-12 02:38 UTC, Firesphere commented on _config/debugbar.yml
> +  show_namespaces: false
That doesn't make sense considering all other database configs are in the same config block as well.

Either split it all out and have the config all over the place, or have it grouped in one place.

2017-07-12 02:39 UTC, robbieaverill commented on _config/debugbar.yml
> +  show_namespaces: false
Can you at least document the change? We've got a list in docs/en/configuration.md and a comment would be good too

2017-07-12 02:40 UTC, Firesphere commented on _config/debugbar.yml
> +  show_namespaces: false
There's a comment

2017-07-12 03:31 UTC, Firesphere commented
Added docs to configuration.md

2017-07-12 03:32 UTC, robbieaverill approved these changes

2017-07-12 03:40 UTC, merged